version: '3'
services:
  
    app:
        build: .
        ports:
            - '3000:3000'
        environment: 
            TYPEORM_CONNECTION: postgres
            TYPEORM_HOST: postgres
            TYPEORM_USERNAME: postgres
            TYPEORM_PASSWORD: password
            TYPEORM_DATABASE: users_ms
            TYPEORM_PORT: 5432
            TYPEORM_ENTITIES: "src/**/*.model.js"
            TYPEORM_ENTITIES_DIR: "src/models"
            TYPEORM_MIGRATIONS: "src/migrations/**/*.js"
            TYPEORM_MIGRATIONS_DIR: "src/migrations"  
        depends_on:
            - postgres
        networks:
            - app-network

    postgres:
        build: .docker/postgres
        tty: true
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: "users_ms"
            POSTGRES_PASSWORD: "password"
            POSTGRES_USER: "postgres"
        networks:
            - app-network
        volumes:
            - .docker/postgres/input/users.csv:/input/users.csv
            - .docker/postgres/input/lista_relevancia_1.txt:/input/lista_relevancia_1.txt
            - .docker/postgres/input/lista_relevancia_2.txt:/input/lista_relevancia_2.txt
            - .docker/postgres/sql/1-init.sql:/docker-entrypoint-initdb.d/1-init.sql
            - .docker/postgres/sql/2-functions.sql:/docker-entrypoint-initdb.d/2-functions.sql
            - .docker/postgres/sql/3-data.sql:/docker-entrypoint-initdb.d/3-data.sql
            - .docker/postgres/sql/4-drop_temp.sql:/docker-entrypoint-initdb.d/4-drop_temp.sql
            - .docker/dbdata:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        ports:
            - '8081:80'
        depends_on:
            - postgres
        # volumes:
        #     - ./dbdata/pgadmin:/var/lib/pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@admin"
            PGADMIN_DEFAULT_PASSWORD: "password"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
